### ISSUE TITLE
Not available on Ubuntu 18.04

### ISSUE THREAD

**Issue by beruic** [jaspernbrouwer/powerline-gitstatus#29]
In your README.md you write that `powerline-gitstatus` can be installed with the command

    apt install powerline-gitstatus

I'm on Ubuntu 18.04, and that package is not available in the default repositories.

**Comment by jcharaoui** [comment]
The package is indeed [available](https://packages.ubuntu.com/search?keywords=powerline-gitstatus&searchon=names&suite=cosmic&section=all), in Ubuntu 18.10.

You can request a backport for 18.04 by following the [Ubuntu Backports procedure](https://wiki.ubuntu.com/UbuntuBackports).

**Comment by orion434** [comment]
It should be a version for Ubuntu 18.04 since it is the LTS (and not the 18.10).

Link to the opened Backport procedure:
https://bugs.launchpad.net/bionic-backports/+bug/1813544

Is there any other way it would be possible to manually compile it and install it?

**Comment by beruic** [comment]
@orion434 Well, since the new LTS is out, is there any reason for bothering?

**Comment by orion434** [comment]
@beruic First of all, it is called LTS because it is supposed to get long term support until the establish date, for 18.04 is April 2023. If a software or package should have a new or legacy version, it should be targeted for on of the LTS (e.g. 18.04 instead of 18.10)

Second, not all people might update or reinstall the new version as soon as they came out. Unfortunately, I was not able to find statistics on Ubuntu version usage and market share. This could be a personal choice or mandated by company policies. Indeed, I am a developer and I have different version installed to make sure that software for the previous LTS is working on those machine until the end support data.
